### ISSUE TITLE
PushConfig.js not created, npm 7.6.0, ignite 2.0.0

### ISSUE THREAD

**Issue by levi-beers** [ryanlntn/ignite-push-notification#1]
When I add ignite-push-notification to a new project it fails to setup PushConfig.js. Same thing occurs on my iMac. 

Levis-MacBook-Pro:IgniteDemo levibeers$ ignite add ignite-push-notification
✖ Path to copy doesn't exist /Users/levibeers/app_tests/IgniteDemo/node_modules/ignite-push-notification/templates/PushConfig.js

**Comment by projectn3xt** [comment]
same here

**Comment by lyrl** [comment]
please fix that

**Comment by levi-beers** [comment]
Pretty sure no one is maintaining this anymore :( I've had success integrating OneSignal into RN apps.

**Comment by valinaga** [comment]
Apparently it tries to copy the PushConfig.js from plugin template directory to app config directory.
But that file exists there already, so you only need to complete the iOS and Android install.

**Comment by rdewolff** [comment]
Same issue here.

This line is not executed : 

https://github.com/ryanlntn/ignite-push-notification/blob/master/plugin.js#L16

You can do it by hand :)

**Comment by ryanlntn** [comment]
This is fixed in 0.0.3
